// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: META-INF/CDTPPackage.proto

package com.syswin.temail.cdtpserver.entity;

public final class CDTPPackageProto {
  private CDTPPackageProto() {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public interface CDTPPackageOrBuilder extends
  // @@protoc_insertion_point(interface_extends:com.syswin.temail.CDTPPackage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 command = 1;</code>
     */
    int getCommand();

    /**
     * <code>int32 version = 2;</code>
     */
    int getVersion();

    /**
     * <code>int32 algorithm = 3;</code>
     */
    int getAlgorithm();

    /**
     * <code>string sign = 4;</code>
     */
    java.lang.String getSign();

    /**
     * <code>string sign = 4;</code>
     */
    com.google.protobuf.ByteString getSignBytes();

    /**
     * <code>int32 dem = 5;</code>
     */
    int getDem();

    /**
     * <code>fixed64 timestamp = 6;</code>
     */
    long getTimestamp();

    /**
     * <code>string pkgId = 7;</code>
     */
    java.lang.String getPkgId();

    /**
     * <code>string pkgId = 7;</code>
     */
    com.google.protobuf.ByteString getPkgIdBytes();

    /**
     * <code>string from = 8;</code>
     */
    java.lang.String getFrom();

    /**
     * <code>string from = 8;</code>
     */
    com.google.protobuf.ByteString getFromBytes();

    /**
     * <code>string to = 9;</code>
     */
    java.lang.String getTo();

    /**
     * <code>string to = 9;</code>
     */
    com.google.protobuf.ByteString getToBytes();

    /**
     * <code>string senderPK = 10;</code>
     */
    java.lang.String getSenderPK();

    /**
     * <code>string senderPK = 10;</code>
     */
    com.google.protobuf.ByteString getSenderPKBytes();

    /**
     * <code>string receiverPK = 11;</code>
     */
    java.lang.String getReceiverPK();

    /**
     * <code>string receiverPK = 11;</code>
     */
    com.google.protobuf.ByteString getReceiverPKBytes();

    /**
     * <code>bytes data = 12;</code>
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code com.syswin.temail.CDTPPackage}
   */
  public static final class CDTPPackage extends com.google.protobuf.GeneratedMessageV3 implements
  // @@protoc_insertion_point(message_implements:com.syswin.temail.CDTPPackage)
      CDTPPackageOrBuilder {
    private static final long serialVersionUID = 0L;

    // Use CDTPPackage.newBuilder() to construct.
    private CDTPPackage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }

    private CDTPPackage() {
      command_ = 0;
      version_ = 0;
      algorithm_ = 0;
      sign_ = "";
      dem_ = 0;
      timestamp_ = 0L;
      pkgId_ = "";
      from_ = "";
      to_ = "";
      senderPK_ = "";
      receiverPK_ = "";
      data_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
      return this.unknownFields;
    }

    private CDTPPackage(com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              command_ = input.readInt32();
              break;
            }
            case 16: {

              version_ = input.readInt32();
              break;
            }
            case 24: {

              algorithm_ = input.readInt32();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              sign_ = s;
              break;
            }
            case 40: {

              dem_ = input.readInt32();
              break;
            }
            case 49: {

              timestamp_ = input.readFixed64();
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              pkgId_ = s;
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              from_ = s;
              break;
            }
            case 74: {
              java.lang.String s = input.readStringRequireUtf8();

              to_ = s;
              break;
            }
            case 82: {
              java.lang.String s = input.readStringRequireUtf8();

              senderPK_ = s;
              break;
            }
            case 90: {
              java.lang.String s = input.readStringRequireUtf8();

              receiverPK_ = s;
              break;
            }
            case 98: {

              data_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }

    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return com.syswin.temail.cdtpserver.entity.CDTPPackageProto.internal_static_com_syswin_temail_CDTPPackage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
      return com.syswin.temail.cdtpserver.entity.CDTPPackageProto.internal_static_com_syswin_temail_CDTPPackage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.syswin.temail.cdtpserver.entity.CDTPPackageProto.CDTPPackage.class,
              com.syswin.temail.cdtpserver.entity.CDTPPackageProto.CDTPPackage.Builder.class);
    }

    public static final int COMMAND_FIELD_NUMBER = 1;
    private int command_;

    /**
     * <code>int32 command = 1;</code>
     */
    public int getCommand() {
      return command_;
    }

    public static final int VERSION_FIELD_NUMBER = 2;
    private int version_;

    /**
     * <code>int32 version = 2;</code>
     */
    public int getVersion() {
      return version_;
    }

    public static final int ALGORITHM_FIELD_NUMBER = 3;
    private int algorithm_;

    /**
     * <code>int32 algorithm = 3;</code>
     */
    public int getAlgorithm() {
      return algorithm_;
    }

    public static final int SIGN_FIELD_NUMBER = 4;
    private volatile java.lang.Object sign_;

    /**
     * <code>string sign = 4;</code>
     */
    public java.lang.String getSign() {
      java.lang.Object ref = sign_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sign_ = s;
        return s;
      }
    }

    /**
     * <code>string sign = 4;</code>
     */
    public com.google.protobuf.ByteString getSignBytes() {
      java.lang.Object ref = sign_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        sign_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DEM_FIELD_NUMBER = 5;
    private int dem_;

    /**
     * <code>int32 dem = 5;</code>
     */
    public int getDem() {
      return dem_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 6;
    private long timestamp_;

    /**
     * <code>fixed64 timestamp = 6;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int PKGID_FIELD_NUMBER = 7;
    private volatile java.lang.Object pkgId_;

    /**
     * <code>string pkgId = 7;</code>
     */
    public java.lang.String getPkgId() {
      java.lang.Object ref = pkgId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pkgId_ = s;
        return s;
      }
    }

    /**
     * <code>string pkgId = 7;</code>
     */
    public com.google.protobuf.ByteString getPkgIdBytes() {
      java.lang.Object ref = pkgId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        pkgId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FROM_FIELD_NUMBER = 8;
    private volatile java.lang.Object from_;

    /**
     * <code>string from = 8;</code>
     */
    public java.lang.String getFrom() {
      java.lang.Object ref = from_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        from_ = s;
        return s;
      }
    }

    /**
     * <code>string from = 8;</code>
     */
    public com.google.protobuf.ByteString getFromBytes() {
      java.lang.Object ref = from_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        from_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TO_FIELD_NUMBER = 9;
    private volatile java.lang.Object to_;

    /**
     * <code>string to = 9;</code>
     */
    public java.lang.String getTo() {
      java.lang.Object ref = to_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        to_ = s;
        return s;
      }
    }

    /**
     * <code>string to = 9;</code>
     */
    public com.google.protobuf.ByteString getToBytes() {
      java.lang.Object ref = to_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        to_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SENDERPK_FIELD_NUMBER = 10;
    private volatile java.lang.Object senderPK_;

    /**
     * <code>string senderPK = 10;</code>
     */
    public java.lang.String getSenderPK() {
      java.lang.Object ref = senderPK_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        senderPK_ = s;
        return s;
      }
    }

    /**
     * <code>string senderPK = 10;</code>
     */
    public com.google.protobuf.ByteString getSenderPKBytes() {
      java.lang.Object ref = senderPK_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        senderPK_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RECEIVERPK_FIELD_NUMBER = 11;
    private volatile java.lang.Object receiverPK_;

    /**
     * <code>string receiverPK = 11;</code>
     */
    public java.lang.String getReceiverPK() {
      java.lang.Object ref = receiverPK_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        receiverPK_ = s;
        return s;
      }
    }

    /**
     * <code>string receiverPK = 11;</code>
     */
    public com.google.protobuf.ByteString getReceiverPKBytes() {
      java.lang.Object ref = receiverPK_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        receiverPK_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATA_FIELD_NUMBER = 12;
    private com.google.protobuf.ByteString data_;

    /**
     * <code>bytes data = 12;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1)
        return true;
      if (isInitialized == 0)
        return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
      if (command_ != 0) {
        output.writeInt32(1, command_);
      }
      if (version_ != 0) {
        output.writeInt32(2, version_);
      }
      if (algorithm_ != 0) {
        output.writeInt32(3, algorithm_);
      }
      if (!getSignBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, sign_);
      }
      if (dem_ != 0) {
        output.writeInt32(5, dem_);
      }
      if (timestamp_ != 0L) {
        output.writeFixed64(6, timestamp_);
      }
      if (!getPkgIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, pkgId_);
      }
      if (!getFromBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, from_);
      }
      if (!getToBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, to_);
      }
      if (!getSenderPKBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, senderPK_);
      }
      if (!getReceiverPKBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 11, receiverPK_);
      }
      if (!data_.isEmpty()) {
        output.writeBytes(12, data_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1)
        return size;

      size = 0;
      if (command_ != 0) {
        size += com.google.protobuf.CodedOutputStream.computeInt32Size(1, command_);
      }
      if (version_ != 0) {
        size += com.google.protobuf.CodedOutputStream.computeInt32Size(2, version_);
      }
      if (algorithm_ != 0) {
        size += com.google.protobuf.CodedOutputStream.computeInt32Size(3, algorithm_);
      }
      if (!getSignBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, sign_);
      }
      if (dem_ != 0) {
        size += com.google.protobuf.CodedOutputStream.computeInt32Size(5, dem_);
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream.computeFixed64Size(6, timestamp_);
      }
      if (!getPkgIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, pkgId_);
      }
      if (!getFromBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, from_);
      }
      if (!getToBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, to_);
      }
      if (!getSenderPKBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, senderPK_);
      }
      if (!getReceiverPKBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, receiverPK_);
      }
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream.computeBytesSize(12, data_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof com.syswin.temail.cdtpserver.entity.CDTPPackageProto.CDTPPackage)) {
        return super.equals(obj);
      }
      com.syswin.temail.cdtpserver.entity.CDTPPackageProto.CDTPPackage other =
          (com.syswin.temail.cdtpserver.entity.CDTPPackageProto.CDTPPackage) obj;

      boolean result = true;
      result = result && (getCommand() == other.getCommand());
      result = result && (getVersion() == other.getVersion());
      result = result && (getAlgorithm() == other.getAlgorithm());
      result = result && getSign().equals(other.getSign());
      result = result && (getDem() == other.getDem());
      result = result && (getTimestamp() == other.getTimestamp());
      result = result && getPkgId().equals(other.getPkgId());
      result = result && getFrom().equals(other.getFrom());
      result = result && getTo().equals(other.getTo());
      result = result && getSenderPK().equals(other.getSenderPK());
      result = result && getReceiverPK().equals(other.getReceiverPK());
      result = result && getData().equals(other.getData());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + COMMAND_FIELD_NUMBER;
      hash = (53 * hash) + getCommand();
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion();
      hash = (37 * hash) + ALGORITHM_FIELD_NUMBER;
      hash = (53 * hash) + getAlgorithm();
      hash = (37 * hash) + SIGN_FIELD_NUMBER;
      hash = (53 * hash) + getSign().hashCode();
      hash = (37 * hash) + DEM_FIELD_NUMBER;
      hash = (53 * hash) + getDem();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(getTimestamp());
      hash = (37 * hash) + PKGID_FIELD_NUMBER;
      hash = (53 * hash) + getPkgId().hashCode();
      hash = (37 * hash) + FROM_FIELD_NUMBER;
      hash = (53 * hash) + getFrom().hashCode();
      hash = (37 * hash) + TO_FIELD_NUMBER;
      hash = (53 * hash) + getTo().hashCode();
      hash = (37 * hash) + SENDERPK_FIELD_NUMBER;
      hash = (53 * hash) + getSenderPK().hashCode();
      hash = (37 * hash) + RECEIVERPK_FIELD_NUMBER;
      hash = (53 * hash) + getReceiverPK().hashCode();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.syswin.temail.cdtpserver.entity.CDTPPackageProto.CDTPPackage parseFrom(
        java.nio.ByteBuffer data) throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.syswin.temail.cdtpserver.entity.CDTPPackageProto.CDTPPackage parseFrom(
        java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.syswin.temail.cdtpserver.entity.CDTPPackageProto.CDTPPackage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.syswin.temail.cdtpserver.entity.CDTPPackageProto.CDTPPackage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.syswin.temail.cdtpserver.entity.CDTPPackageProto.CDTPPackage parseFrom(
        byte[] data) throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.syswin.temail.cdtpserver.entity.CDTPPackageProto.CDTPPackage parseFrom(
        byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.syswin.temail.cdtpserver.entity.CDTPPackageProto.CDTPPackage parseFrom(
        java.io.InputStream input) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static com.syswin.temail.cdtpserver.entity.CDTPPackageProto.CDTPPackage parseFrom(
        java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input,
          extensionRegistry);
    }

    public static com.syswin.temail.cdtpserver.entity.CDTPPackageProto.CDTPPackage parseDelimitedFrom(
        java.io.InputStream input) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
    }

    public static com.syswin.temail.cdtpserver.entity.CDTPPackageProto.CDTPPackage parseDelimitedFrom(
        java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input,
          extensionRegistry);
    }

    public static com.syswin.temail.cdtpserver.entity.CDTPPackageProto.CDTPPackage parseFrom(
        com.google.protobuf.CodedInputStream input) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static com.syswin.temail.cdtpserver.entity.CDTPPackageProto.CDTPPackage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input,
          extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
      return newBuilder();
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(
        com.syswin.temail.cdtpserver.entity.CDTPPackageProto.CDTPPackage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }

    /**
     * Protobuf type {@code com.syswin.temail.CDTPPackage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
    // @@protoc_insertion_point(builder_implements:com.syswin.temail.CDTPPackage)
        com.syswin.temail.cdtpserver.entity.CDTPPackageProto.CDTPPackageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
        return com.syswin.temail.cdtpserver.entity.CDTPPackageProto.internal_static_com_syswin_temail_CDTPPackage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
        return com.syswin.temail.cdtpserver.entity.CDTPPackageProto.internal_static_com_syswin_temail_CDTPPackage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.syswin.temail.cdtpserver.entity.CDTPPackageProto.CDTPPackage.class,
                com.syswin.temail.cdtpserver.entity.CDTPPackageProto.CDTPPackage.Builder.class);
      }

      // Construct using
      // com.syswin.temail.cdtpserver.entity.CDTPPackageProto.CDTPPackage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
        }
      }

      @java.lang.Override
      public Builder clear() {
        super.clear();
        command_ = 0;

        version_ = 0;

        algorithm_ = 0;

        sign_ = "";

        dem_ = 0;

        timestamp_ = 0L;

        pkgId_ = "";

        from_ = "";

        to_ = "";

        senderPK_ = "";

        receiverPK_ = "";

        data_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
        return com.syswin.temail.cdtpserver.entity.CDTPPackageProto.internal_static_com_syswin_temail_CDTPPackage_descriptor;
      }

      @java.lang.Override
      public com.syswin.temail.cdtpserver.entity.CDTPPackageProto.CDTPPackage getDefaultInstanceForType() {
        return com.syswin.temail.cdtpserver.entity.CDTPPackageProto.CDTPPackage
            .getDefaultInstance();
      }

      @java.lang.Override
      public com.syswin.temail.cdtpserver.entity.CDTPPackageProto.CDTPPackage build() {
        com.syswin.temail.cdtpserver.entity.CDTPPackageProto.CDTPPackage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.syswin.temail.cdtpserver.entity.CDTPPackageProto.CDTPPackage buildPartial() {
        com.syswin.temail.cdtpserver.entity.CDTPPackageProto.CDTPPackage result =
            new com.syswin.temail.cdtpserver.entity.CDTPPackageProto.CDTPPackage(this);
        result.command_ = command_;
        result.version_ = version_;
        result.algorithm_ = algorithm_;
        result.sign_ = sign_;
        result.dem_ = dem_;
        result.timestamp_ = timestamp_;
        result.pkgId_ = pkgId_;
        result.from_ = from_;
        result.to_ = to_;
        result.senderPK_ = senderPK_;
        result.receiverPK_ = receiverPK_;
        result.data_ = data_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }

      @java.lang.Override
      public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }

      @java.lang.Override
      public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }

      @java.lang.Override
      public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }

      @java.lang.Override
      public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }

      @java.lang.Override
      public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.syswin.temail.cdtpserver.entity.CDTPPackageProto.CDTPPackage) {
          return mergeFrom((com.syswin.temail.cdtpserver.entity.CDTPPackageProto.CDTPPackage) other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(
          com.syswin.temail.cdtpserver.entity.CDTPPackageProto.CDTPPackage other) {
        if (other == com.syswin.temail.cdtpserver.entity.CDTPPackageProto.CDTPPackage
            .getDefaultInstance())
          return this;
        if (other.getCommand() != 0) {
          setCommand(other.getCommand());
        }
        if (other.getVersion() != 0) {
          setVersion(other.getVersion());
        }
        if (other.getAlgorithm() != 0) {
          setAlgorithm(other.getAlgorithm());
        }
        if (!other.getSign().isEmpty()) {
          sign_ = other.sign_;
          onChanged();
        }
        if (other.getDem() != 0) {
          setDem(other.getDem());
        }
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        if (!other.getPkgId().isEmpty()) {
          pkgId_ = other.pkgId_;
          onChanged();
        }
        if (!other.getFrom().isEmpty()) {
          from_ = other.from_;
          onChanged();
        }
        if (!other.getTo().isEmpty()) {
          to_ = other.to_;
          onChanged();
        }
        if (!other.getSenderPK().isEmpty()) {
          senderPK_ = other.senderPK_;
          onChanged();
        }
        if (!other.getReceiverPK().isEmpty()) {
          receiverPK_ = other.receiverPK_;
          onChanged();
        }
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        com.syswin.temail.cdtpserver.entity.CDTPPackageProto.CDTPPackage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage =
              (com.syswin.temail.cdtpserver.entity.CDTPPackageProto.CDTPPackage) e
                  .getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int command_;

      /**
       * <code>int32 command = 1;</code>
       */
      public int getCommand() {
        return command_;
      }

      /**
       * <code>int32 command = 1;</code>
       */
      public Builder setCommand(int value) {

        command_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>int32 command = 1;</code>
       */
      public Builder clearCommand() {

        command_ = 0;
        onChanged();
        return this;
      }

      private int version_;

      /**
       * <code>int32 version = 2;</code>
       */
      public int getVersion() {
        return version_;
      }

      /**
       * <code>int32 version = 2;</code>
       */
      public Builder setVersion(int value) {

        version_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>int32 version = 2;</code>
       */
      public Builder clearVersion() {

        version_ = 0;
        onChanged();
        return this;
      }

      private int algorithm_;

      /**
       * <code>int32 algorithm = 3;</code>
       */
      public int getAlgorithm() {
        return algorithm_;
      }

      /**
       * <code>int32 algorithm = 3;</code>
       */
      public Builder setAlgorithm(int value) {

        algorithm_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>int32 algorithm = 3;</code>
       */
      public Builder clearAlgorithm() {

        algorithm_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object sign_ = "";

      /**
       * <code>string sign = 4;</code>
       */
      public java.lang.String getSign() {
        java.lang.Object ref = sign_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sign_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }

      /**
       * <code>string sign = 4;</code>
       */
      public com.google.protobuf.ByteString getSignBytes() {
        java.lang.Object ref = sign_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
          sign_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      /**
       * <code>string sign = 4;</code>
       */
      public Builder setSign(java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        sign_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>string sign = 4;</code>
       */
      public Builder clearSign() {

        sign_ = getDefaultInstance().getSign();
        onChanged();
        return this;
      }

      /**
       * <code>string sign = 4;</code>
       */
      public Builder setSignBytes(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        sign_ = value;
        onChanged();
        return this;
      }

      private int dem_;

      /**
       * <code>int32 dem = 5;</code>
       */
      public int getDem() {
        return dem_;
      }

      /**
       * <code>int32 dem = 5;</code>
       */
      public Builder setDem(int value) {

        dem_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>int32 dem = 5;</code>
       */
      public Builder clearDem() {

        dem_ = 0;
        onChanged();
        return this;
      }

      private long timestamp_;

      /**
       * <code>fixed64 timestamp = 6;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }

      /**
       * <code>fixed64 timestamp = 6;</code>
       */
      public Builder setTimestamp(long value) {

        timestamp_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>fixed64 timestamp = 6;</code>
       */
      public Builder clearTimestamp() {

        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object pkgId_ = "";

      /**
       * <code>string pkgId = 7;</code>
       */
      public java.lang.String getPkgId() {
        java.lang.Object ref = pkgId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          pkgId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }

      /**
       * <code>string pkgId = 7;</code>
       */
      public com.google.protobuf.ByteString getPkgIdBytes() {
        java.lang.Object ref = pkgId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
          pkgId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      /**
       * <code>string pkgId = 7;</code>
       */
      public Builder setPkgId(java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        pkgId_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>string pkgId = 7;</code>
       */
      public Builder clearPkgId() {

        pkgId_ = getDefaultInstance().getPkgId();
        onChanged();
        return this;
      }

      /**
       * <code>string pkgId = 7;</code>
       */
      public Builder setPkgIdBytes(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        pkgId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object from_ = "";

      /**
       * <code>string from = 8;</code>
       */
      public java.lang.String getFrom() {
        java.lang.Object ref = from_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          from_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }

      /**
       * <code>string from = 8;</code>
       */
      public com.google.protobuf.ByteString getFromBytes() {
        java.lang.Object ref = from_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
          from_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      /**
       * <code>string from = 8;</code>
       */
      public Builder setFrom(java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        from_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>string from = 8;</code>
       */
      public Builder clearFrom() {

        from_ = getDefaultInstance().getFrom();
        onChanged();
        return this;
      }

      /**
       * <code>string from = 8;</code>
       */
      public Builder setFromBytes(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        from_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object to_ = "";

      /**
       * <code>string to = 9;</code>
       */
      public java.lang.String getTo() {
        java.lang.Object ref = to_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          to_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }

      /**
       * <code>string to = 9;</code>
       */
      public com.google.protobuf.ByteString getToBytes() {
        java.lang.Object ref = to_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
          to_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      /**
       * <code>string to = 9;</code>
       */
      public Builder setTo(java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        to_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>string to = 9;</code>
       */
      public Builder clearTo() {

        to_ = getDefaultInstance().getTo();
        onChanged();
        return this;
      }

      /**
       * <code>string to = 9;</code>
       */
      public Builder setToBytes(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        to_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object senderPK_ = "";

      /**
       * <code>string senderPK = 10;</code>
       */
      public java.lang.String getSenderPK() {
        java.lang.Object ref = senderPK_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          senderPK_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }

      /**
       * <code>string senderPK = 10;</code>
       */
      public com.google.protobuf.ByteString getSenderPKBytes() {
        java.lang.Object ref = senderPK_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
          senderPK_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      /**
       * <code>string senderPK = 10;</code>
       */
      public Builder setSenderPK(java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        senderPK_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>string senderPK = 10;</code>
       */
      public Builder clearSenderPK() {

        senderPK_ = getDefaultInstance().getSenderPK();
        onChanged();
        return this;
      }

      /**
       * <code>string senderPK = 10;</code>
       */
      public Builder setSenderPKBytes(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        senderPK_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object receiverPK_ = "";

      /**
       * <code>string receiverPK = 11;</code>
       */
      public java.lang.String getReceiverPK() {
        java.lang.Object ref = receiverPK_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          receiverPK_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }

      /**
       * <code>string receiverPK = 11;</code>
       */
      public com.google.protobuf.ByteString getReceiverPKBytes() {
        java.lang.Object ref = receiverPK_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
          receiverPK_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      /**
       * <code>string receiverPK = 11;</code>
       */
      public Builder setReceiverPK(java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        receiverPK_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>string receiverPK = 11;</code>
       */
      public Builder clearReceiverPK() {

        receiverPK_ = getDefaultInstance().getReceiverPK();
        onChanged();
        return this;
      }

      /**
       * <code>string receiverPK = 11;</code>
       */
      public Builder setReceiverPKBytes(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        receiverPK_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;

      /**
       * <code>bytes data = 12;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }

      /**
       * <code>bytes data = 12;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }

        data_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>bytes data = 12;</code>
       */
      public Builder clearData() {

        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      @java.lang.Override
      public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.syswin.temail.CDTPPackage)
    }

    // @@protoc_insertion_point(class_scope:com.syswin.temail.CDTPPackage)
    private static final com.syswin.temail.cdtpserver.entity.CDTPPackageProto.CDTPPackage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.syswin.temail.cdtpserver.entity.CDTPPackageProto.CDTPPackage();
    }

    public static com.syswin.temail.cdtpserver.entity.CDTPPackageProto.CDTPPackage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CDTPPackage> PARSER =
        new com.google.protobuf.AbstractParser<CDTPPackage>() {
          @java.lang.Override
          public CDTPPackage parsePartialFrom(com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
            return new CDTPPackage(input, extensionRegistry);
          }
        };

    public static com.google.protobuf.Parser<CDTPPackage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CDTPPackage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.syswin.temail.cdtpserver.entity.CDTPPackageProto.CDTPPackage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor internal_static_com_syswin_temail_CDTPPackage_descriptor;
  private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_com_syswin_temail_CDTPPackage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
  static {
    java.lang.String[] descriptorData =
        {"\n\032META-INF/CDTPPackage.proto\022\021com.syswin"
            + ".temail\"\315\001\n\013CDTPPackage\022\017\n\007command\030\001 \001(\005"
            + "\022\017\n\007version\030\002 \001(\005\022\021\n\talgorithm\030\003 \001(\005\022\014\n\004"
            + "sign\030\004 \001(\t\022\013\n\003dem\030\005 \001(\005\022\021\n\ttimestamp\030\006 \001"
            + "(\006\022\r\n\005pkgId\030\007 \001(\t\022\014\n\004from\030\010 \001(\t\022\n\n\002to\030\t "
            + "\001(\t\022\020\n\010senderPK\030\n \001(\t\022\022\n\nreceiverPK\030\013 \001("
            + "\t\022\014\n\004data\030\014 \001(\014B7\n#com.syswin.temail.cdt"
            + "pserver.entityB\020CDTPPackageProtob\006proto3"};
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {}, assigner);
    internal_static_com_syswin_temail_CDTPPackage_descriptor =
        getDescriptor().getMessageTypes().get(0);
    internal_static_com_syswin_temail_CDTPPackage_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_com_syswin_temail_CDTPPackage_descriptor, new java.lang.String[] {
                "Command", "Version", "Algorithm", "Sign", "Dem", "Timestamp", "PkgId", "From",
                "To", "SenderPK", "ReceiverPK", "Data",});
  }

  // @@protoc_insertion_point(outer_class_scope)
}
