// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: META-INF/Header.proto

package com.syswin.temail.gateway.entity;

public final class CDTPHeaderProto {
  private CDTPHeaderProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CDTPHeaderOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.syswin.temail.gateway.Header)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string deviceId = 1;</code>
     */
    java.lang.String getDeviceId();
    /**
     * <code>string deviceId = 1;</code>
     */
    com.google.protobuf.ByteString
        getDeviceIdBytes();

    /**
     * <code>int32 signatureAlgorithm = 2;</code>
     */
    int getSignatureAlgorithm();

    /**
     * <code>string signature = 3;</code>
     */
    java.lang.String getSignature();
    /**
     * <code>string signature = 3;</code>
     */
    com.google.protobuf.ByteString
        getSignatureBytes();

    /**
     * <code>int32 dataEncryptionMethod = 4;</code>
     */
    int getDataEncryptionMethod();

    /**
     * <code>fixed64 timestamp = 5;</code>
     */
    long getTimestamp();

    /**
     * <code>string packetId = 6;</code>
     */
    java.lang.String getPacketId();
    /**
     * <code>string packetId = 6;</code>
     */
    com.google.protobuf.ByteString
        getPacketIdBytes();

    /**
     * <code>string sender = 7;</code>
     */
    java.lang.String getSender();
    /**
     * <code>string sender = 7;</code>
     */
    com.google.protobuf.ByteString
        getSenderBytes();

    /**
     * <code>string senderPK = 8;</code>
     */
    java.lang.String getSenderPK();
    /**
     * <code>string senderPK = 8;</code>
     */
    com.google.protobuf.ByteString
        getSenderPKBytes();

    /**
     * <code>string receiver = 9;</code>
     */
    java.lang.String getReceiver();
    /**
     * <code>string receiver = 9;</code>
     */
    com.google.protobuf.ByteString
        getReceiverBytes();

    /**
     * <code>string receiverPK = 10;</code>
     */
    java.lang.String getReceiverPK();
    /**
     * <code>string receiverPK = 10;</code>
     */
    com.google.protobuf.ByteString
        getReceiverPKBytes();

    /**
     * <code>string at = 11;</code>
     */
    java.lang.String getAt();
    /**
     * <code>string at = 11;</code>
     */
    com.google.protobuf.ByteString
        getAtBytes();

    /**
     * <code>string topic = 12;</code>
     */
    java.lang.String getTopic();
    /**
     * <code>string topic = 12;</code>
     */
    com.google.protobuf.ByteString
        getTopicBytes();

    /**
     * <code>string extraData = 13;</code>
     */
    java.lang.String getExtraData();
    /**
     * <code>string extraData = 13;</code>
     */
    com.google.protobuf.ByteString
        getExtraDataBytes();
  }
  /**
   * Protobuf type {@code com.syswin.temail.gateway.Header}
   */
  public  static final class CDTPHeader extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.syswin.temail.gateway.Header)
      CDTPHeaderOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Header.newBuilder() to construct.
    private CDTPHeader(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CDTPHeader() {
      deviceId_ = "";
      signatureAlgorithm_ = 0;
      signature_ = "";
      dataEncryptionMethod_ = 0;
      timestamp_ = 0L;
      packetId_ = "";
      sender_ = "";
      senderPK_ = "";
      receiver_ = "";
      receiverPK_ = "";
      at_ = "";
      topic_ = "";
      extraData_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CDTPHeader(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              deviceId_ = s;
              break;
            }
            case 16: {

              signatureAlgorithm_ = input.readInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              signature_ = s;
              break;
            }
            case 32: {

              dataEncryptionMethod_ = input.readInt32();
              break;
            }
            case 41: {

              timestamp_ = input.readFixed64();
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              packetId_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              sender_ = s;
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              senderPK_ = s;
              break;
            }
            case 74: {
              java.lang.String s = input.readStringRequireUtf8();

              receiver_ = s;
              break;
            }
            case 82: {
              java.lang.String s = input.readStringRequireUtf8();

              receiverPK_ = s;
              break;
            }
            case 90: {
              java.lang.String s = input.readStringRequireUtf8();

              at_ = s;
              break;
            }
            case 98: {
              java.lang.String s = input.readStringRequireUtf8();

              topic_ = s;
              break;
            }
            case 106: {
              java.lang.String s = input.readStringRequireUtf8();

              extraData_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.syswin.temail.gateway.entity.CDTPHeaderProto.internal_static_com_syswin_temail_gateway_CDTPHeader_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.syswin.temail.gateway.entity.CDTPHeaderProto.internal_static_com_syswin_temail_gateway_CDTPHeader_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.syswin.temail.gateway.entity.CDTPHeaderProto.CDTPHeader.class, com.syswin.temail.gateway.entity.CDTPHeaderProto.CDTPHeader.Builder.class);
    }

    public static final int DEVICEID_FIELD_NUMBER = 1;
    private volatile java.lang.Object deviceId_;
    /**
     * <code>string deviceId = 1;</code>
     */
    public java.lang.String getDeviceId() {
      java.lang.Object ref = deviceId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deviceId_ = s;
        return s;
      }
    }
    /**
     * <code>string deviceId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceIdBytes() {
      java.lang.Object ref = deviceId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SIGNATUREALGORITHM_FIELD_NUMBER = 2;
    private int signatureAlgorithm_;
    /**
     * <code>int32 signatureAlgorithm = 2;</code>
     */
    public int getSignatureAlgorithm() {
      return signatureAlgorithm_;
    }

    public static final int SIGNATURE_FIELD_NUMBER = 3;
    private volatile java.lang.Object signature_;
    /**
     * <code>string signature = 3;</code>
     */
    public java.lang.String getSignature() {
      java.lang.Object ref = signature_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        signature_ = s;
        return s;
      }
    }
    /**
     * <code>string signature = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSignatureBytes() {
      java.lang.Object ref = signature_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        signature_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATAENCRYPTIONMETHOD_FIELD_NUMBER = 4;
    private int dataEncryptionMethod_;
    /**
     * <code>int32 dataEncryptionMethod = 4;</code>
     */
    public int getDataEncryptionMethod() {
      return dataEncryptionMethod_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 5;
    private long timestamp_;
    /**
     * <code>fixed64 timestamp = 5;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int PACKETID_FIELD_NUMBER = 6;
    private volatile java.lang.Object packetId_;
    /**
     * <code>string packetId = 6;</code>
     */
    public java.lang.String getPacketId() {
      java.lang.Object ref = packetId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        packetId_ = s;
        return s;
      }
    }
    /**
     * <code>string packetId = 6;</code>
     */
    public com.google.protobuf.ByteString
        getPacketIdBytes() {
      java.lang.Object ref = packetId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        packetId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SENDER_FIELD_NUMBER = 7;
    private volatile java.lang.Object sender_;
    /**
     * <code>string sender = 7;</code>
     */
    public java.lang.String getSender() {
      java.lang.Object ref = sender_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sender_ = s;
        return s;
      }
    }
    /**
     * <code>string sender = 7;</code>
     */
    public com.google.protobuf.ByteString
        getSenderBytes() {
      java.lang.Object ref = sender_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sender_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SENDERPK_FIELD_NUMBER = 8;
    private volatile java.lang.Object senderPK_;
    /**
     * <code>string senderPK = 8;</code>
     */
    public java.lang.String getSenderPK() {
      java.lang.Object ref = senderPK_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        senderPK_ = s;
        return s;
      }
    }
    /**
     * <code>string senderPK = 8;</code>
     */
    public com.google.protobuf.ByteString
        getSenderPKBytes() {
      java.lang.Object ref = senderPK_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        senderPK_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RECEIVER_FIELD_NUMBER = 9;
    private volatile java.lang.Object receiver_;
    /**
     * <code>string receiver = 9;</code>
     */
    public java.lang.String getReceiver() {
      java.lang.Object ref = receiver_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        receiver_ = s;
        return s;
      }
    }
    /**
     * <code>string receiver = 9;</code>
     */
    public com.google.protobuf.ByteString
        getReceiverBytes() {
      java.lang.Object ref = receiver_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        receiver_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RECEIVERPK_FIELD_NUMBER = 10;
    private volatile java.lang.Object receiverPK_;
    /**
     * <code>string receiverPK = 10;</code>
     */
    public java.lang.String getReceiverPK() {
      java.lang.Object ref = receiverPK_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        receiverPK_ = s;
        return s;
      }
    }
    /**
     * <code>string receiverPK = 10;</code>
     */
    public com.google.protobuf.ByteString
        getReceiverPKBytes() {
      java.lang.Object ref = receiverPK_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        receiverPK_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AT_FIELD_NUMBER = 11;
    private volatile java.lang.Object at_;
    /**
     * <code>string at = 11;</code>
     */
    public java.lang.String getAt() {
      java.lang.Object ref = at_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        at_ = s;
        return s;
      }
    }
    /**
     * <code>string at = 11;</code>
     */
    public com.google.protobuf.ByteString
        getAtBytes() {
      java.lang.Object ref = at_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        at_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOPIC_FIELD_NUMBER = 12;
    private volatile java.lang.Object topic_;
    /**
     * <code>string topic = 12;</code>
     */
    public java.lang.String getTopic() {
      java.lang.Object ref = topic_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        topic_ = s;
        return s;
      }
    }
    /**
     * <code>string topic = 12;</code>
     */
    public com.google.protobuf.ByteString
        getTopicBytes() {
      java.lang.Object ref = topic_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        topic_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXTRADATA_FIELD_NUMBER = 13;
    private volatile java.lang.Object extraData_;
    /**
     * <code>string extraData = 13;</code>
     */
    public java.lang.String getExtraData() {
      java.lang.Object ref = extraData_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        extraData_ = s;
        return s;
      }
    }
    /**
     * <code>string extraData = 13;</code>
     */
    public com.google.protobuf.ByteString
        getExtraDataBytes() {
      java.lang.Object ref = extraData_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        extraData_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getDeviceIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, deviceId_);
      }
      if (signatureAlgorithm_ != 0) {
        output.writeInt32(2, signatureAlgorithm_);
      }
      if (!getSignatureBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, signature_);
      }
      if (dataEncryptionMethod_ != 0) {
        output.writeInt32(4, dataEncryptionMethod_);
      }
      if (timestamp_ != 0L) {
        output.writeFixed64(5, timestamp_);
      }
      if (!getPacketIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, packetId_);
      }
      if (!getSenderBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, sender_);
      }
      if (!getSenderPKBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, senderPK_);
      }
      if (!getReceiverBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, receiver_);
      }
      if (!getReceiverPKBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, receiverPK_);
      }
      if (!getAtBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 11, at_);
      }
      if (!getTopicBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 12, topic_);
      }
      if (!getExtraDataBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 13, extraData_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getDeviceIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, deviceId_);
      }
      if (signatureAlgorithm_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, signatureAlgorithm_);
      }
      if (!getSignatureBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, signature_);
      }
      if (dataEncryptionMethod_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, dataEncryptionMethod_);
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed64Size(5, timestamp_);
      }
      if (!getPacketIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, packetId_);
      }
      if (!getSenderBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, sender_);
      }
      if (!getSenderPKBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, senderPK_);
      }
      if (!getReceiverBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, receiver_);
      }
      if (!getReceiverPKBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, receiverPK_);
      }
      if (!getAtBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, at_);
      }
      if (!getTopicBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, topic_);
      }
      if (!getExtraDataBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, extraData_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.syswin.temail.gateway.entity.CDTPHeaderProto.CDTPHeader)) {
        return super.equals(obj);
      }
      com.syswin.temail.gateway.entity.CDTPHeaderProto.CDTPHeader other = (com.syswin.temail.gateway.entity.CDTPHeaderProto.CDTPHeader) obj;

      boolean result = true;
      result = result && getDeviceId()
          .equals(other.getDeviceId());
      result = result && (getSignatureAlgorithm()
          == other.getSignatureAlgorithm());
      result = result && getSignature()
          .equals(other.getSignature());
      result = result && (getDataEncryptionMethod()
          == other.getDataEncryptionMethod());
      result = result && (getTimestamp()
          == other.getTimestamp());
      result = result && getPacketId()
          .equals(other.getPacketId());
      result = result && getSender()
          .equals(other.getSender());
      result = result && getSenderPK()
          .equals(other.getSenderPK());
      result = result && getReceiver()
          .equals(other.getReceiver());
      result = result && getReceiverPK()
          .equals(other.getReceiverPK());
      result = result && getAt()
          .equals(other.getAt());
      result = result && getTopic()
          .equals(other.getTopic());
      result = result && getExtraData()
          .equals(other.getExtraData());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DEVICEID_FIELD_NUMBER;
      hash = (53 * hash) + getDeviceId().hashCode();
      hash = (37 * hash) + SIGNATUREALGORITHM_FIELD_NUMBER;
      hash = (53 * hash) + getSignatureAlgorithm();
      hash = (37 * hash) + SIGNATURE_FIELD_NUMBER;
      hash = (53 * hash) + getSignature().hashCode();
      hash = (37 * hash) + DATAENCRYPTIONMETHOD_FIELD_NUMBER;
      hash = (53 * hash) + getDataEncryptionMethod();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (37 * hash) + PACKETID_FIELD_NUMBER;
      hash = (53 * hash) + getPacketId().hashCode();
      hash = (37 * hash) + SENDER_FIELD_NUMBER;
      hash = (53 * hash) + getSender().hashCode();
      hash = (37 * hash) + SENDERPK_FIELD_NUMBER;
      hash = (53 * hash) + getSenderPK().hashCode();
      hash = (37 * hash) + RECEIVER_FIELD_NUMBER;
      hash = (53 * hash) + getReceiver().hashCode();
      hash = (37 * hash) + RECEIVERPK_FIELD_NUMBER;
      hash = (53 * hash) + getReceiverPK().hashCode();
      hash = (37 * hash) + AT_FIELD_NUMBER;
      hash = (53 * hash) + getAt().hashCode();
      hash = (37 * hash) + TOPIC_FIELD_NUMBER;
      hash = (53 * hash) + getTopic().hashCode();
      hash = (37 * hash) + EXTRADATA_FIELD_NUMBER;
      hash = (53 * hash) + getExtraData().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.syswin.temail.gateway.entity.CDTPHeaderProto.CDTPHeader parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.syswin.temail.gateway.entity.CDTPHeaderProto.CDTPHeader parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.syswin.temail.gateway.entity.CDTPHeaderProto.CDTPHeader parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.syswin.temail.gateway.entity.CDTPHeaderProto.CDTPHeader parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.syswin.temail.gateway.entity.CDTPHeaderProto.CDTPHeader parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.syswin.temail.gateway.entity.CDTPHeaderProto.CDTPHeader parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.syswin.temail.gateway.entity.CDTPHeaderProto.CDTPHeader parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.syswin.temail.gateway.entity.CDTPHeaderProto.CDTPHeader parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.syswin.temail.gateway.entity.CDTPHeaderProto.CDTPHeader parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.syswin.temail.gateway.entity.CDTPHeaderProto.CDTPHeader parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.syswin.temail.gateway.entity.CDTPHeaderProto.CDTPHeader parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.syswin.temail.gateway.entity.CDTPHeaderProto.CDTPHeader parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.syswin.temail.gateway.entity.CDTPHeaderProto.CDTPHeader prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.syswin.temail.gateway.Header}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.syswin.temail.gateway.Header)
        com.syswin.temail.gateway.entity.CDTPHeaderProto.CDTPHeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.syswin.temail.gateway.entity.CDTPHeaderProto.internal_static_com_syswin_temail_gateway_CDTPHeader_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.syswin.temail.gateway.entity.CDTPHeaderProto.internal_static_com_syswin_temail_gateway_CDTPHeader_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.syswin.temail.gateway.entity.CDTPHeaderProto.CDTPHeader.class, com.syswin.temail.gateway.entity.CDTPHeaderProto.CDTPHeader.Builder.class);
      }

      // Construct using com.syswin.temail.gateway.entity.CDTPHeaderProto.Header.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        deviceId_ = "";

        signatureAlgorithm_ = 0;

        signature_ = "";

        dataEncryptionMethod_ = 0;

        timestamp_ = 0L;

        packetId_ = "";

        sender_ = "";

        senderPK_ = "";

        receiver_ = "";

        receiverPK_ = "";

        at_ = "";

        topic_ = "";

        extraData_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.syswin.temail.gateway.entity.CDTPHeaderProto.internal_static_com_syswin_temail_gateway_CDTPHeader_descriptor;
      }

      @java.lang.Override
      public com.syswin.temail.gateway.entity.CDTPHeaderProto.CDTPHeader getDefaultInstanceForType() {
        return com.syswin.temail.gateway.entity.CDTPHeaderProto.CDTPHeader.getDefaultInstance();
      }

      @java.lang.Override
      public com.syswin.temail.gateway.entity.CDTPHeaderProto.CDTPHeader build() {
        com.syswin.temail.gateway.entity.CDTPHeaderProto.CDTPHeader result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.syswin.temail.gateway.entity.CDTPHeaderProto.CDTPHeader buildPartial() {
        com.syswin.temail.gateway.entity.CDTPHeaderProto.CDTPHeader result = new com.syswin.temail.gateway.entity.CDTPHeaderProto.CDTPHeader(this);
        result.deviceId_ = deviceId_;
        result.signatureAlgorithm_ = signatureAlgorithm_;
        result.signature_ = signature_;
        result.dataEncryptionMethod_ = dataEncryptionMethod_;
        result.timestamp_ = timestamp_;
        result.packetId_ = packetId_;
        result.sender_ = sender_;
        result.senderPK_ = senderPK_;
        result.receiver_ = receiver_;
        result.receiverPK_ = receiverPK_;
        result.at_ = at_;
        result.topic_ = topic_;
        result.extraData_ = extraData_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.syswin.temail.gateway.entity.CDTPHeaderProto.CDTPHeader) {
          return mergeFrom((com.syswin.temail.gateway.entity.CDTPHeaderProto.CDTPHeader)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.syswin.temail.gateway.entity.CDTPHeaderProto.CDTPHeader other) {
        if (other == com.syswin.temail.gateway.entity.CDTPHeaderProto.CDTPHeader.getDefaultInstance()) return this;
        if (!other.getDeviceId().isEmpty()) {
          deviceId_ = other.deviceId_;
          onChanged();
        }
        if (other.getSignatureAlgorithm() != 0) {
          setSignatureAlgorithm(other.getSignatureAlgorithm());
        }
        if (!other.getSignature().isEmpty()) {
          signature_ = other.signature_;
          onChanged();
        }
        if (other.getDataEncryptionMethod() != 0) {
          setDataEncryptionMethod(other.getDataEncryptionMethod());
        }
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        if (!other.getPacketId().isEmpty()) {
          packetId_ = other.packetId_;
          onChanged();
        }
        if (!other.getSender().isEmpty()) {
          sender_ = other.sender_;
          onChanged();
        }
        if (!other.getSenderPK().isEmpty()) {
          senderPK_ = other.senderPK_;
          onChanged();
        }
        if (!other.getReceiver().isEmpty()) {
          receiver_ = other.receiver_;
          onChanged();
        }
        if (!other.getReceiverPK().isEmpty()) {
          receiverPK_ = other.receiverPK_;
          onChanged();
        }
        if (!other.getAt().isEmpty()) {
          at_ = other.at_;
          onChanged();
        }
        if (!other.getTopic().isEmpty()) {
          topic_ = other.topic_;
          onChanged();
        }
        if (!other.getExtraData().isEmpty()) {
          extraData_ = other.extraData_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.syswin.temail.gateway.entity.CDTPHeaderProto.CDTPHeader parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.syswin.temail.gateway.entity.CDTPHeaderProto.CDTPHeader) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object deviceId_ = "";
      /**
       * <code>string deviceId = 1;</code>
       */
      public java.lang.String getDeviceId() {
        java.lang.Object ref = deviceId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          deviceId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string deviceId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getDeviceIdBytes() {
        java.lang.Object ref = deviceId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          deviceId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string deviceId = 1;</code>
       */
      public Builder setDeviceId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        deviceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string deviceId = 1;</code>
       */
      public Builder clearDeviceId() {
        
        deviceId_ = getDefaultInstance().getDeviceId();
        onChanged();
        return this;
      }
      /**
       * <code>string deviceId = 1;</code>
       */
      public Builder setDeviceIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        deviceId_ = value;
        onChanged();
        return this;
      }

      private int signatureAlgorithm_ ;
      /**
       * <code>int32 signatureAlgorithm = 2;</code>
       */
      public int getSignatureAlgorithm() {
        return signatureAlgorithm_;
      }
      /**
       * <code>int32 signatureAlgorithm = 2;</code>
       */
      public Builder setSignatureAlgorithm(int value) {
        
        signatureAlgorithm_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 signatureAlgorithm = 2;</code>
       */
      public Builder clearSignatureAlgorithm() {
        
        signatureAlgorithm_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object signature_ = "";
      /**
       * <code>string signature = 3;</code>
       */
      public java.lang.String getSignature() {
        java.lang.Object ref = signature_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          signature_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string signature = 3;</code>
       */
      public com.google.protobuf.ByteString
          getSignatureBytes() {
        java.lang.Object ref = signature_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          signature_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string signature = 3;</code>
       */
      public Builder setSignature(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        signature_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string signature = 3;</code>
       */
      public Builder clearSignature() {
        
        signature_ = getDefaultInstance().getSignature();
        onChanged();
        return this;
      }
      /**
       * <code>string signature = 3;</code>
       */
      public Builder setSignatureBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        signature_ = value;
        onChanged();
        return this;
      }

      private int dataEncryptionMethod_ ;
      /**
       * <code>int32 dataEncryptionMethod = 4;</code>
       */
      public int getDataEncryptionMethod() {
        return dataEncryptionMethod_;
      }
      /**
       * <code>int32 dataEncryptionMethod = 4;</code>
       */
      public Builder setDataEncryptionMethod(int value) {
        
        dataEncryptionMethod_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 dataEncryptionMethod = 4;</code>
       */
      public Builder clearDataEncryptionMethod() {
        
        dataEncryptionMethod_ = 0;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>fixed64 timestamp = 5;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>fixed64 timestamp = 5;</code>
       */
      public Builder setTimestamp(long value) {
        
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>fixed64 timestamp = 5;</code>
       */
      public Builder clearTimestamp() {
        
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object packetId_ = "";
      /**
       * <code>string packetId = 6;</code>
       */
      public java.lang.String getPacketId() {
        java.lang.Object ref = packetId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          packetId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string packetId = 6;</code>
       */
      public com.google.protobuf.ByteString
          getPacketIdBytes() {
        java.lang.Object ref = packetId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          packetId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string packetId = 6;</code>
       */
      public Builder setPacketId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        packetId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string packetId = 6;</code>
       */
      public Builder clearPacketId() {
        
        packetId_ = getDefaultInstance().getPacketId();
        onChanged();
        return this;
      }
      /**
       * <code>string packetId = 6;</code>
       */
      public Builder setPacketIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        packetId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object sender_ = "";
      /**
       * <code>string sender = 7;</code>
       */
      public java.lang.String getSender() {
        java.lang.Object ref = sender_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sender_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string sender = 7;</code>
       */
      public com.google.protobuf.ByteString
          getSenderBytes() {
        java.lang.Object ref = sender_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sender_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string sender = 7;</code>
       */
      public Builder setSender(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sender_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string sender = 7;</code>
       */
      public Builder clearSender() {
        
        sender_ = getDefaultInstance().getSender();
        onChanged();
        return this;
      }
      /**
       * <code>string sender = 7;</code>
       */
      public Builder setSenderBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sender_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object senderPK_ = "";
      /**
       * <code>string senderPK = 8;</code>
       */
      public java.lang.String getSenderPK() {
        java.lang.Object ref = senderPK_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          senderPK_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string senderPK = 8;</code>
       */
      public com.google.protobuf.ByteString
          getSenderPKBytes() {
        java.lang.Object ref = senderPK_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          senderPK_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string senderPK = 8;</code>
       */
      public Builder setSenderPK(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        senderPK_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string senderPK = 8;</code>
       */
      public Builder clearSenderPK() {
        
        senderPK_ = getDefaultInstance().getSenderPK();
        onChanged();
        return this;
      }
      /**
       * <code>string senderPK = 8;</code>
       */
      public Builder setSenderPKBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        senderPK_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object receiver_ = "";
      /**
       * <code>string receiver = 9;</code>
       */
      public java.lang.String getReceiver() {
        java.lang.Object ref = receiver_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          receiver_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string receiver = 9;</code>
       */
      public com.google.protobuf.ByteString
          getReceiverBytes() {
        java.lang.Object ref = receiver_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          receiver_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string receiver = 9;</code>
       */
      public Builder setReceiver(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        receiver_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string receiver = 9;</code>
       */
      public Builder clearReceiver() {
        
        receiver_ = getDefaultInstance().getReceiver();
        onChanged();
        return this;
      }
      /**
       * <code>string receiver = 9;</code>
       */
      public Builder setReceiverBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        receiver_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object receiverPK_ = "";
      /**
       * <code>string receiverPK = 10;</code>
       */
      public java.lang.String getReceiverPK() {
        java.lang.Object ref = receiverPK_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          receiverPK_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string receiverPK = 10;</code>
       */
      public com.google.protobuf.ByteString
          getReceiverPKBytes() {
        java.lang.Object ref = receiverPK_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          receiverPK_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string receiverPK = 10;</code>
       */
      public Builder setReceiverPK(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        receiverPK_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string receiverPK = 10;</code>
       */
      public Builder clearReceiverPK() {
        
        receiverPK_ = getDefaultInstance().getReceiverPK();
        onChanged();
        return this;
      }
      /**
       * <code>string receiverPK = 10;</code>
       */
      public Builder setReceiverPKBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        receiverPK_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object at_ = "";
      /**
       * <code>string at = 11;</code>
       */
      public java.lang.String getAt() {
        java.lang.Object ref = at_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          at_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string at = 11;</code>
       */
      public com.google.protobuf.ByteString
          getAtBytes() {
        java.lang.Object ref = at_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          at_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string at = 11;</code>
       */
      public Builder setAt(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        at_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string at = 11;</code>
       */
      public Builder clearAt() {
        
        at_ = getDefaultInstance().getAt();
        onChanged();
        return this;
      }
      /**
       * <code>string at = 11;</code>
       */
      public Builder setAtBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        at_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object topic_ = "";
      /**
       * <code>string topic = 12;</code>
       */
      public java.lang.String getTopic() {
        java.lang.Object ref = topic_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          topic_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string topic = 12;</code>
       */
      public com.google.protobuf.ByteString
          getTopicBytes() {
        java.lang.Object ref = topic_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          topic_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string topic = 12;</code>
       */
      public Builder setTopic(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        topic_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string topic = 12;</code>
       */
      public Builder clearTopic() {
        
        topic_ = getDefaultInstance().getTopic();
        onChanged();
        return this;
      }
      /**
       * <code>string topic = 12;</code>
       */
      public Builder setTopicBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        topic_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object extraData_ = "";
      /**
       * <code>string extraData = 13;</code>
       */
      public java.lang.String getExtraData() {
        java.lang.Object ref = extraData_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          extraData_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string extraData = 13;</code>
       */
      public com.google.protobuf.ByteString
          getExtraDataBytes() {
        java.lang.Object ref = extraData_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          extraData_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string extraData = 13;</code>
       */
      public Builder setExtraData(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        extraData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string extraData = 13;</code>
       */
      public Builder clearExtraData() {
        
        extraData_ = getDefaultInstance().getExtraData();
        onChanged();
        return this;
      }
      /**
       * <code>string extraData = 13;</code>
       */
      public Builder setExtraDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        extraData_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.syswin.temail.gateway.Header)
    }

    // @@protoc_insertion_point(class_scope:com.syswin.temail.gateway.Header)
    private static final com.syswin.temail.gateway.entity.CDTPHeaderProto.CDTPHeader DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.syswin.temail.gateway.entity.CDTPHeaderProto.CDTPHeader();
    }

    public static com.syswin.temail.gateway.entity.CDTPHeaderProto.CDTPHeader getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CDTPHeader>
        PARSER = new com.google.protobuf.AbstractParser<CDTPHeader>() {
      @java.lang.Override
      public CDTPHeader parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CDTPHeader(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CDTPHeader> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CDTPHeader> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.syswin.temail.gateway.entity.CDTPHeaderProto.CDTPHeader getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_syswin_temail_gateway_CDTPHeader_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_syswin_temail_gateway_CDTPHeader_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031META-INF/Header.proto\022\031com.syswin." +
      "temail.gateway\"\206\002\n\nHeader\022\020\n\010deviceI" +
      "d\030\001 \001(\t\022\032\n\022signatureAlgorithm\030\002 \001(\005\022\021\n\ts" +
      "ignature\030\003 \001(\t\022\034\n\024dataEncryptionMethod\030\004" +
      " \001(\005\022\021\n\ttimestamp\030\005 \001(\006\022\020\n\010packetId\030\006 \001(" +
      "\t\022\016\n\006sender\030\007 \001(\t\022\020\n\010senderPK\030\010 \001(\t\022\020\n\010r" +
      "eceiver\030\t \001(\t\022\022\n\nreceiverPK\030\n \001(\t\022\n\n\002at\030" +
      "\013 \001(\t\022\r\n\005topic\030\014 \001(\t\022\021\n\textraData\030\r \001(\tB" +
      "3\n com.syswin.temail.gateway.entityB\017CDT" +
      "PHeaderProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_syswin_temail_gateway_CDTPHeader_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_syswin_temail_gateway_CDTPHeader_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_syswin_temail_gateway_CDTPHeader_descriptor,
        new java.lang.String[] { "DeviceId", "SignatureAlgorithm", "Signature", "DataEncryptionMethod", "Timestamp", "PacketId", "Sender", "SenderPK", "Receiver", "ReceiverPK", "At", "Topic", "ExtraData", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
